# Generated by Django 5.0.4 on 2024-04-22 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=512)),
                ("author", models.CharField(max_length=64)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "date_published",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 4, 22, 14, 42, 1, 674873, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
