# Generated by Django 5.0.4 on 2024-04-22 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_published",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
